module.exports = options => {
    return {
        Addr1: "string",
        Addr2: "string",
        Addr3: "string",
        AllocationCode: "string",
        CaseDateFormat: "string",
        CaseExpirationFlag: "string",
        CaseJulianDateFlag: "string",
        CasePackDateFlag: "string",
        CaseSellByFlag: "string",
        City: "string",
        //ColdStorageFacility: "boolean",
        ContactName: "string",
        Country: "string",
        CustAbbrev: "string",
        CustName: "string",
        CustNum: "string",
        CustShortName: "string",
        DateCreated: "date",
        DescWithDiscount: "string",
        DescWithoutDiscount: "string",
        //FacilityType: "string",
        FaxNum: "string",
        FileType: "string",
        //GLN: "string",
        //IncludeOnRSCSReport: "boolean",
        Notes: "string",
        PackageName: "string",
        PhoneNum: "string",
        PkgExpirationFlag: "string",
        PkgJulianDateFlag: "string",
        PkgPackDateFlag: "string",
        PkgSellByFlag: "string",
        //PlantId: "integer", DO NOT USE PlantId in ORM
        PriceCheckDigit: "string",
        //RSCSFacilityCode: "string",
        ShipToNum: "string",
        State: "string",
        TareTableIndex: "string",
        TransDate: "date",
        TransTime: "string",
        TraySellByFlag: "string",
        Zip: "string",
        //Following are NVP values from Progress
        ScaleGroup: 'string',
    }
}