module.exports = options => {
    return {
        OrdNum: 'string',
        OrdRefLine: 'integer',
        ProdCode: 'integer',
        PrePrice: 'decimal',
        ReqCount: 'integer',
        ShippedCount: 'integer',
        NetWgtShipped: 'decimal',
        SaleItem: 'integer',
        SellByOffset: 'integer',
        AllowedAge: 'integer',
        SellByOnCase: 'boolean',
        TareToUse: 'decimal',
        TraysPerCase: 'integer',
        Mrk_Down_Method: 'string',
        PlantId: { type: 'integer', defaultValueOnInsert: 0, preventUpdate: true },
        Discount: 'decimal',
        Descr_Discount_Card: 'string',
        Desc_wo_Disc_Card: 'string',
        UPCCode: 'string',
        TareDesc: 'string',
        FixPrice: 'decimal',
        MarkDownPrice: 'string',
        CouponType: 'string',
        CatchWgtId: 'string',
        DnLineNum: 'string',
        NameValuePairs: 'string',
        WarehouseCode: 'string',
        BranchCode: 'string',
        SellByDate: 'date',
        LinkCode: 'string',
        Agecode: 'integer',
        UpdateDays: 'integer',
        CreateDateTime: { type: 'datetime', defaultValueOnInsert: 'CURRENT_TIMESTAMP', preventUpdate: true, preventSelection: true },
        ModifyDateTime: { type: 'datetime', defaultValueOnInsert: 'CURRENT_TIMESTAMP', defaultValueOnUpdate: 'CURRENT_TIMESTAMP',  preventSelection: true },
    }
}