module.exports = options => {
    return {
        OrdNum: 'string',
        Tare: 'string',
        CustNum: 'string',
        Case_Count: 'integer',
        CustAbbrev: 'string',
        ReqShipDate: 'date',
        ReqShipTime: 'time',
        ReqArrDate: 'date',
        ReqArrTime: 'time',
        // CompletionDate: 'date',
        // CompletionTime: 'time',
        Pack_Name: 'string',
        Modular_Flag: 'string',
        Modular_Pallet: 'string',
        Produced_Date: 'date',
        Produced_Time: 'time',
        RouteNum: 'string',
        LoadSeq: 'integer',
        Moved_To_Orderh: 'boolean',
        PONum: 'string',
        SalesRep: 'string',
        BarCode_Format: 'integer',
        Barcode_Chk_Dig: 'integer',
        //PlantId:{type:'integer',defaultValueOnInsert:options.plantid},
        ChangeDate: 'date',
        ChangeTime: 'time',
        LoadNumber: 'string',
        USDAPlant: 'string',
        StopNum: 'integer',
        DeliveryNUm: { type: 'string', alternatives: ['DeliveryNum', 'DeliveryNumber'] },
        PlantCode: 'string',
        ShipToName: 'string',
        ShipToAddr1: 'string',
        ShipToAddr2: 'string',
        ShipToCity: 'string',
        ShipToState: 'string',
        ShipToCountry: 'string',
        ShipToZip: 'string',
        Carrier: 'string',
        Instructions: 'string',
        OrderDate: 'date',
        OrderTime: 'time',
        NameValuePairs: 'string',
        RouteDescription: 'string',
        CarrierName: 'string',
        SecondaryCarrierCode: 'string',
        ERPPlantID: 'string',
        BOLNumber: 'string',
        PaymentTerms: 'string',
        LoadStopNumber: 'integer',
        SendAck: 'boolean',
        CreateDateTime: { type: 'datetime', defaultValueOnInsert: 'CURRENT_TIMESTAMP', preventUpdate: true, preventSelection: true },
        ModifyDateTime: { type: 'datetime', defaultValueOnInsert: 'CURRENT_TIMESTAMP', defaultValueOnUpdate: 'CURRENT_TIMESTAMP',  preventSelection: true },
    }
}