module.exports = options => {
    return {
        OrdNum: 'string',
        OrdRefLine: 'integer',
        ProdCode: 'integer',
        PrePrice: 'decimal',
        ReqCount: 'integer',
        TareIndex: 'integer',
        //PlantId:{type:'integer',defaultValueOnInsert:options.plantid,preventUpdate:true},
        UPCCode: 'string',
        TareDesc: 'string',
        FixPrice: 'decimal',
        MarkDownPrice: 'decimal',
        DnLineNum: 'string',
        AllowedAge: 'integer',
        MrkDownMethod: 'string',
        CouponType: 'string',
        CatchWgtId: 'string',
        ReqShipDate: 'date',
        ReqShipTime: 'time',
        ReqArrDate: 'date',
        ReqArrTime: 'time',
        // CompletionDate: 'date',
        // CompletionTime: 'time',
        LoadSeq: 'integer',
        PONum: 'string',
        LoadNumber: 'string',
        USDAPlant: 'string',
        StopNum: 'integer',
        DeliveryNUm: { type: 'string', alternatives: ['DeliveryNum', 'DeliveryNumber'] },
        PlantCode: 'string',
        StoreLoc: 'string',
        rejectres: 'string',
        CUSPIndicator: 'string',
        CUSPOrder: 'string',
        CUSPOrdItem: 'string',
        AllocationCode: 'string',
        NameValuePairs: 'string',
        StatusCode: 'integer',
        WarehouseCode: 'string',
        BranchCode: 'string'
    }
}