module.exports = options => {
    return {
        AllocationCode:'string',
        ArbDate:'date',
        BoxTareWgt:'decimal',
        CatchWeight:'decimal',
        DelLinNum:'integer',
        DelNum:'string',
        DetailStatus:'string',
        KillDate:'date',
        LabelDate:'date',
        LabelTime:'time',
        LabelWgt:'decimal',
        Lot:'string',        
        NameValuePairs:'string',
        NetWgt:'decimal',
        PalletNum:'string',
        PdnDate:'date',
        PdnLoc:'string',
        PdnOperator:'string',
        PdnOrdLineNum:'integer',
        PdnOrdNum:'string',
        PdnSrcCode:'string',
        PdnTime:'time',
        Price:'decimal',
        PrintDate:'date',
        PrintTime:'time',
        prodcode:'string',        
        SellByDate:'date',
        SerialNum:'string',
        Shift:'integer',
        StatusCodes:'string',
        TareWgt:'decimal',
        UnitsPerBox:'integer',
        WgtTypeCode:'string',
        WO_Number:'integer',
        CreateDateTime: { type: 'datetime', defaultValueOnInsert: 'SYSTIMESTAMP', preventUpdate: true, preventSelection: true },
        ModifyDateTime: { type: 'datetime', defaultValueOnInsert: 'SYSTIMESTAMP', defaultValueOnUpdate: 'SYSTIMESTAMP',  preventSelection: true },
        //RecordSeq:{type:'integer',insertSequence:'AsnDetail-seq'},
        _nvp:{
            Serialized:'string',
            SSCC18Barcode:'string',
        }
    }
}