module.exports = options => {
    return {
        CanMoveBoxesIn: {type:"boolean", defaultValueOnInsert:false},
        CanMoveBoxesOut: {type:"boolean", defaultValueOnInsert:false},
        Descr: {type:"string"},
        IsBinLocation: {type:"boolean", defaultValueOnInsert:false},
        IsHoldLocation: {type:"boolean", defaultValueOnInsert:false},
        IsInvLocation: {type:"boolean", defaultValueOnInsert:false},
        IsLoadArea: {type:"boolean"},
        IsPickLocation: {type:"boolean", defaultValueOnInsert:false},
        IsProductionLocation: {type:"boolean", defaultValueOnInsert:false},
        IsRackLocation: {type:"boolean", defaultValueOnInsert:false},
        IsReworkLocation: {type:"boolean", defaultValueOnInsert:false},
        IsTermLocation: {type:"boolean", defaultValueOnInsert:false},
        LocCode: {type:"string", requiredOnInsert:true},
        LocGroup: {type:"string"},
        LocType: {type:"string"},
        //NameValuePairs: {type:"string"},
        NumPalletsAllowed: {type:"integer"},
        OrdNum: {type:"string"},
        OtherFlags: {type:"string"},
        PlantId:{type:'integer',defaultValueOnInsert:options.plantid,preventUpdate:true},
        ZuluDepartment: {type:"string"},
        CreateDateTime: { type: 'datetime', defaultValueOnInsert: 'SYSTIMESTAMP', preventUpdate: true, preventSelection: true },
        ModifyDateTime: { type: 'datetime', defaultValueOnInsert: 'SYSTIMESTAMP', defaultValueOnUpdate: 'SYSTIMESTAMP',  preventSelection: true },
        //RecordSeq:{type:'integer',insertSequence:'Location-seq'},
    }
}