module.exports = options => {
    return {
        OrdNum: 'string',
        OrdRefLine: 'integer',
        ProdCode: 'integer',
        PrePrice: 'decimal',
        ReqCount: 'integer',
        TareIndex: 'integer',
        PlantId:{type:'integer',defaultValueOnInsert:options.plantid,preventUpdate:true},
        UPCCode: 'string',
        TareDesc: 'string',
        FixPrice: 'decimal',
        MarkDownPrice: 'decimal',
        DnLineNum: 'string',
        AllowedAge: 'integer',
        MrkDownMethod: 'string',
        CouponType: 'string',
        CatchWgtId: 'string',
        ReqShipDate: 'date',
        ReqShipTime: {type:'time',format:'HHmm'},
        ReqArrDate: 'date',
        ReqArrTime: {type:'time',format:'HHmm'},
        CompletionDate: 'date',
        CompletionTime: {type:'time',format:'HHmm'},
        LoadSeq: 'integer',
        PONum: 'string',
        LoadNumber: 'string',
        USDAPlant: 'string',
        StopNum: 'integer',
        DeliveryNUm: {type:'string',alternatives:['DeliveryNum','DeliveryNumber']},
        PlantCode: 'string',
        StoreLoc: 'string',
        rejectres: 'string',
        CUSPIndicator: 'string',
        CUSPOrder: 'string',
        CUSPOrdItem: 'string',
        AllocationCode: 'string',
        NameValuePairs: 'string',
        StatusCode: 'integer',
        WarehouseCode: 'string',
        BranchCode: 'string',
        CreateDateTime: { type: 'datetime', defaultValueOnInsert: 'SYSTIMESTAMP', preventUpdate: true, preventSelection: true },
        ModifyDateTime: { type: 'datetime', defaultValueOnInsert: 'SYSTIMESTAMP', defaultValueOnUpdate: 'SYSTIMESTAMP',  preventSelection: true },
        //RecordSeq:{type:'integer',insertSequence:'SAP-MIS-OD-seq'},
    }
}