module.exports = options => {
    return { 
        SerialNum:{type:'string',preventUpdate:true},
        Bloxnum:{type:'string',alternatives:['BloxNum','bloxNum']},
        CBloxnum:'string',
        Customer:'string',
        BoxTareWgt:'decimal',
        //BatchNum:'integer', //commenting fields that are NOT currently used in Nimbus
        //WPL_Number:'integer', //commenting fields that are NOT currently used in Nimbus
        //WO_Number:'integer', //commenting fields that are NOT currently used in Nimbus
        InvStatCode:'string',
        IsInv:'boolean',
        PlantId:{type:'integer',defaultValueOnInsert:options.plantid,preventUpdate:true},
        DeptCodeDate:'string', 
        DeptNumber:'string', 
        KillDate:'date',
        LabelDate:'date',
        PrintTime:'string',
        LabelTime:'string',
        LabelWgt:'decimal',
        WgtTypeCode:'string',
        LocCode:'string',
        LocDate:'date',
        LocTime:'string',                       
        LocOperator:'string',
        LocDateTime:'datetime',
        LabelDT:'datetime',
        PDNDT:'datetime',
        Lot:'string',
        NetWgt:'decimal',
        OrdNum:'string',
        OrdRefNum:{type:'integer',defaultValueOnInsert:0},
        OrdRefLine:{type:'integer',defaultValueOnInsert:0},
        PalletNum:'string',
        PdnDate:'date',
        PdnTime:'string',
        PdnLoc:'string',
        PdnOperator:'string',
        PdnSrcCode:'string',
        ProdCode:'integer',
        ScaleNum:'integer',
        SerialPlantId:{type:'integer',defaultValueOnInsert:options.plantid},
        Shift:'integer',
        TareWgt:'decimal',
        SellByDate:'date',
        OrigBarCodeScan:'string',
        PdnOrdNum:'string',
        PdnOrdLineNum:'integer',
        ZPDNDeptName:'string',
        NameValuePairs:'string',
        GoalID:'integer',
        AllocationCode:'string',
        CreateDateTime: { type: 'datetime', defaultValueOnInsert: 'SYSTIMESTAMP', preventUpdate: true, preventSelection: true },
        ModifyDateTime: { type: 'datetime', defaultValueOnInsert: 'SYSTIMESTAMP',  preventSelection: true },
        //RecordSeq:{type:'integer',insertSequence:'Serial-seq'},
        _nvp:{
            SSCC18Barcode:'string',
            OriginalAsnPallet:'string',
            // MfgID:'string',
            // DateAI:'integer',
            // DateAIDate:'date',
            // Counter:'integer'
        }
                    
    }
}